language: node_js
node_js: "0.12"
script: npm run travisci
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "SIJPUuVbECDZe1JdmkzKDnpQvc492X5SuAJNfCl1gFIdZ+3Wa3SpFM3uUBTgf81qVIj2bZ8kSamAVNnx4OkM9UlU/trmXzgpFD5tQ0gVtT3tJYuT02oxYKiEPMAAwHF/tmZlgVJDeAVijoYjyh+s9yEY9rJKzWulYCd5O60XV5EXPtI7ynmShh4ghfXEZyiivBUOsQU14re4m2u7IW5un4YFl2j/LHOM+Ntv4aIzwuA1639WRCDyWYSHvZjFkEIBtTgoFZDU6ASR22kG41HIc1nWs1eSmcsTUFVT2Bquxzg/IdMpHi+Rd/+iZYQV5jiI3/u5rSsgIgytDsf3hodxxN7KfeEz02Q1yPj1IeS5hAzxLOqwKqzkaAmjUI5lPfypNtzqLbblZmx/ghON8x50LmSF4/Rf2QOhAK7kd/Sn1/OOy1X547CiCopyWAcE+8ff4fPGYq2eWcrC5LvVF30wNd57uGzWW/dlOFu1g13Nu8on5wZxHsRTxZF+TOaSWxdWkb4pqbmbjtkj4BJNIkdusy5EQc6ARJfH7a0STWTaRf7b34YgwKnapR02Ibe4ngxcEuhNa7knMnfnC7y7YFS0rsQ2Thn+cB7NOV2Kd+n9WRjyQ7KXuFJjcr4dyUu0B8HjY+THAPAv7nUy3ck2vS6Q5ArraEUUrHbxAMsl6GpsVrI="
